train_batch_size : 256
test_batch_size : 1024
n, epochs : 100
r, n_runs : 1
lr : 0.001
optimizer : adam
sigma : 1.0
c, max-per-sample-grad_norm : 0.1
delta : 0.00001
device : cuda
disable_dp : True
data_root : data/
exp_idx : 0
network : ResNet18
dataset : 'cifar10' 
model_dir : './'
trigger_file : './'
checkpoint : './checkpoints'
trigger_path : './BadNet/triggers/trigger_white.png'
trigger_size : 5
trigger_label : 0
poisoning_rate : 0.1
is_backdoored : False
experiment_strings : "dataset"
poison_num : 5000
is_save_each_epoch : False